/*
Mouner Dabjan 
Oct 10 2018 
Make people a pizza 
 */

/**
 *
 * @author modab5310
 */
public class Pitza extends javax.swing.JFrame {

    /**
     * Creates new form Pitza
     */
    public Pitza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Titleew = new javax.swing.JLabel();
        DiameterInput = new javax.swing.JLabel();
        Calculation = new javax.swing.JToggleButton();
        TaxesLabel = new javax.swing.JLabel();
        SubtotalLable = new javax.swing.JLabel();
        GrandLabel = new javax.swing.JLabel();
        DiameterText = new javax.swing.JTextField();
        FinalTax = new javax.swing.JLabel();
        FinalSub = new javax.swing.JLabel();
        finalgrand = new javax.swing.JLabel();
        Pictureeee = new javax.swing.JLabel();
        finalsentencee = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        Titleew.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Titleew.setText("Making A Pizza ");

        DiameterInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DiameterInput.setText("Diameter Of Pizza (cm): ");

        Calculation.setText("CalculatePrice ");
        Calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculationActionPerformed(evt);
            }
        });

        TaxesLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TaxesLabel.setText("Taxes (13%): ");

        SubtotalLable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SubtotalLable.setText("Subtotal ($): ");

        GrandLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        GrandLabel.setText("Grandtotal($): ");

        Pictureeee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (1).jpg"))); // NOI18N

        finalsentencee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(Calculation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DiameterInput)
                        .addGap(18, 18, 18)
                        .addComponent(DiameterText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titleew)))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SubtotalLable)
                                .addGap(18, 18, 18)
                                .addComponent(FinalSub, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TaxesLabel)
                                .addGap(18, 18, 18)
                                .addComponent(FinalTax, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GrandLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finalgrand, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(finalsentencee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(Pictureeee))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titleew)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiameterInput)
                    .addComponent(DiameterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Calculation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TaxesLabel)
                            .addComponent(FinalTax))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubtotalLable)
                            .addComponent(FinalSub))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrandLabel)
                            .addComponent(finalgrand))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalsentencee, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Pictureeee, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculationActionPerformed

        // constants
        final double LABOUR_PRICE = 0.75;
        final double PLACE_RENT = 0.99;
        final double DIAM_PRICE = 0.50;
        final double TAX_RATE = 0.13;

        // variable

        double diam;
        double tax;
        double subtotal;
        double grandtotal;

        // input

        diam = Double.parseDouble(DiameterText.getText());


        // algorithms

        subtotal = (diam * DIAM_PRICE) + LABOUR_PRICE + PLACE_RENT;
        subtotal = subtotal * 100;
        subtotal = Math.round(subtotal); 
        subtotal = subtotal / 100; 
        
        
        tax = subtotal * TAX_RATE;
        tax = tax * 100;
        tax = Math.round(tax); 
        tax = tax / 100; 
        
        
        grandtotal = tax + subtotal;
        grandtotal = grandtotal * 100;
        grandtotal = Math.round(grandtotal);
        grandtotal = grandtotal / 100;


        // output


        FinalTax.setText(String.valueOf(tax));
        FinalSub.setText(String.valueOf(subtotal));
        finalgrand.setText(String.valueOf(grandtotal)); 
        
        // selection statemen
        
        if ((diam>=1) && (diam<=15))
        {
            finalsentencee.setText("We are going to make you a cute little pizza! ");
        }
        else if ((diam>=20) && (diam<=40))
        {
            finalsentencee.setText("This will be delicious"); 
        }
        else if (diam>40)
        {
            finalsentencee.setText("Whoa, big pizza! You might need a truck to get this home!");
        }
           
     
       
    }//GEN-LAST:event_CalculationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pitza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pitza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pitza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pitza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pitza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Calculation;
    private javax.swing.JLabel DiameterInput;
    private javax.swing.JTextField DiameterText;
    private javax.swing.JLabel FinalSub;
    private javax.swing.JLabel FinalTax;
    private javax.swing.JLabel GrandLabel;
    private javax.swing.JLabel Pictureeee;
    private javax.swing.JLabel SubtotalLable;
    private javax.swing.JLabel TaxesLabel;
    private javax.swing.JLabel Titleew;
    private javax.swing.JLabel finalgrand;
    private javax.swing.JLabel finalsentencee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
